// Taskwarrior 3.5's compiled-in `configurationDefaults` (`src/Context.cpp`), which it parses before
// the Taskrc. Comments and alignment are stripped; the parser drops them anyway.
let taskwarriorDefaults = #"""
	data.location=~/.task
	gc=1
	exit.on.missing.db=0
	hooks=1
	detection=1
	defaultwidth=80
	defaultheight=24
	avoidlastcolumn=0
	hyphenate=1
	reserved.lines=1
	verbose=affected,blank,context,edit,header,footnote,label,new-id,news,project,special,sync,override,recur
	confirmation=1
	recurrence=1
	recurrence.confirmation=prompt
	allow.empty.filter=1
	annotation.info=1
	indent.annotation=2
	indent.report=0
	row.padding=0
	column.padding=1
	bulk=3
	nag=You have more urgent tasks.
	search.case.sensitive=1
	active.indicator=*
	tag.indicator=+
	dependency.indicator=D
	recurrence.indicator=R
	recurrence.limit=1
	regex=1
	xterm.title=0
	expressions=infix
	json.array=1
	abbreviation.minimum=2
	news.version=
	purge.on-sync=0
	dateformat=Y-M-D
	dateformat.holiday=YMD
	dateformat.edit=Y-M-D H:N:S
	dateformat.info=Y-M-D H:N:S
	dateformat.report=
	dateformat.annotation=
	date.iso=1
	weekstart=sunday
	displayweeknumber=1
	due=7
	calendar.legend=1
	calendar.details=sparse
	calendar.details.report=list
	calendar.offset=0
	calendar.offset.value=-1
	calendar.holidays=none
	journal.time=0
	journal.time.start.annotation=Started task
	journal.time.stop.annotation=Stopped task
	journal.info=1
	dependency.reminder=1
	dependency.confirmation=1
	urgency.user.tag.next.coefficient=15.0
	urgency.due.coefficient=12.0
	urgency.blocking.coefficient=8.0
	urgency.active.coefficient=4.0
	urgency.scheduled.coefficient=5.0
	urgency.age.coefficient=2.0
	urgency.annotations.coefficient=1.0
	urgency.tags.coefficient=1.0
	urgency.project.coefficient=1.0
	urgency.blocked.coefficient=-5.0
	urgency.waiting.coefficient=-3.0
	urgency.inherit=0
	urgency.age.max=365
	color=1
	include default.theme
	rule.precedence.color=deleted,completed,active,keyword.,tag.,project.,overdue,scheduled,due.today,due,blocked,blocking,recurring,tagged,uda.
	uda.priority.type=string
	uda.priority.label=Priority
	uda.priority.values=H,M,L,
	urgency.uda.priority.H.coefficient=6.0
	urgency.uda.priority.M.coefficient=3.9
	urgency.uda.priority.L.coefficient=1.8
	default.command=next
	default.timesheet.filter=( +PENDING and start.after:now-4wks ) or ( +COMPLETED and end.after:now-4wks )
	_forcecolor=0
	complete.all.tags=0
	list.all.projects=0
	summary.all.projects=0
	list.all.tags=0
	print.empty.columns=0
	debug=0
	sugar=1
	obfuscate=0
	fontunderline=1
	alias.rm=delete
	alias.history=history.monthly
	alias.ghistory=ghistory.monthly
	alias.burndown=burndown.weekly
	report.long.description=All details of tasks
	report.long.labels=ID,A,Created,Mod,Deps,P,Project,Tags,Recur,Wait,Sched,Due,Until,Description
	report.long.columns=id,start.active,entry,modified.age,depends,priority,project,tags,recur,wait.remaining,scheduled,due,until,description
	report.long.filter=+PENDING -WAITING
	report.long.sort=modified-
	report.long.context=1
	report.list.description=Most details of tasks
	report.list.labels=ID,Active,Age,D,P,Project,Tags,R,Sch,Due,Until,Description,Urg
	report.list.columns=id,start.age,entry.age,depends.indicator,priority,project,tags,recur.indicator,scheduled.countdown,due,until.remaining,description.count,urgency
	report.list.filter=+PENDING -WAITING
	report.list.sort=start-,due+,project+,urgency-
	report.list.context=1
	report.ls.description=Few details of tasks
	report.ls.labels=ID,A,D,Project,Tags,R,Wait,S,Due,Until,Description
	report.ls.columns=id,start.active,depends.indicator,project,tags,recur.indicator,wait.remaining,scheduled.countdown,due.countdown,until.countdown,description.count
	report.ls.filter=+PENDING -WAITING
	report.ls.sort=start-,description+
	report.ls.context=1
	report.minimal.description=Minimal details of tasks
	report.minimal.labels=ID,Project,Tags,Description
	report.minimal.columns=id,project,tags.count,description.count
	report.minimal.filter=+PENDING -WAITING
	report.minimal.sort=project+/,description+
	report.minimal.context=1
	report.newest.description=Newest tasks
	report.newest.labels=ID,Active,Created,Age,Mod,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
	report.newest.columns=id,start.age,entry,entry.age,modified.age,depends.indicator,priority,project,tags,recur.indicator,wait.remaining,scheduled.countdown,due,until.age,description
	report.newest.filter=+PENDING -WAITING
	report.newest.sort=entry-
	report.newest.context=1
	report.oldest.description=Oldest tasks
	report.oldest.labels=ID,Active,Created,Age,Mod,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
	report.oldest.columns=id,start.age,entry,entry.age,modified.age,depends.indicator,priority,project,tags,recur.indicator,wait.remaining,scheduled.countdown,due,until.age,description
	report.oldest.filter=+PENDING -WAITING
	report.oldest.sort=entry+
	report.oldest.context=1
	report.overdue.description=Overdue tasks
	report.overdue.labels=ID,Active,Age,Deps,P,Project,Tag,R,S,Due,Until,Description,Urg
	report.overdue.columns=id,start.age,entry.age,depends,priority,project,tags,recur.indicator,scheduled.countdown,due,until,description,urgency
	report.overdue.filter=+PENDING -WAITING +OVERDUE
	report.overdue.sort=urgency-,due+
	report.overdue.context=1
	report.active.description=Active tasks
	report.active.labels=ID,Started,Active,Age,D,P,Project,Tags,Recur,W,Sch,Due,Until,Description
	report.active.columns=id,start,start.age,entry.age,depends.indicator,priority,project,tags,recur,wait,scheduled.remaining,due,until,description
	report.active.filter=+PENDING -WAITING +ACTIVE
	report.active.sort=project+,start+
	report.active.context=1
	report.completed.description=Completed tasks
	report.completed.labels=ID,UUID,Created,Completed,Age,Deps,P,Project,Tags,R,Due,Description
	report.completed.columns=id,uuid.short,entry,end,entry.age,depends,priority,project,tags,recur.indicator,due,description
	report.completed.filter=status:completed -WAITING
	report.completed.sort=end+
	report.completed.context=1
	report.recurring.description=Recurring Tasks
	report.recurring.labels=ID,Active,Age,D,P,Parent,Project,Tags,Recur,Sch,Due,Until,Description,Urg
	report.recurring.columns=id,start.age,entry.age,depends.indicator,priority,parent.short,project,tags,recur,scheduled.countdown,due,until.remaining,description,urgency
	report.recurring.filter=(+PENDING -WAITING +CHILD) or (status:recurring -WAITING +PARENT)
	report.recurring.sort=due+,urgency-,entry+
	report.recurring.context=1
	report.waiting.description=Waiting (hidden) tasks
	report.waiting.labels=ID,A,Age,D,P,Project,Tags,R,Wait,Remaining,Sched,Due,Until,Description
	report.waiting.columns=id,start.active,entry.age,depends.indicator,priority,project,tags,recur.indicator,wait,wait.remaining,scheduled,due,until,description
	report.waiting.filter=+WAITING
	report.waiting.sort=due+,wait+,entry+
	report.waiting.context=1
	report.all.description=All tasks
	report.all.labels=ID,St,UUID,A,Age,Done,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
	report.all.columns=id,status.short,uuid.short,start.active,entry.age,end.age,depends.indicator,priority,project.parent,tags.count,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
	report.all.sort=entry-
	report.all.context=1
	report.next.description=Most urgent tasks
	report.next.labels=ID,Active,Age,Deps,P,Project,Tag,Recur,S,Due,Until,Description,Urg
	report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
	report.next.filter=+PENDING -WAITING limit:page
	report.next.sort=urgency-
	report.next.context=1
	report.ready.description=Most urgent actionable tasks
	report.ready.labels=ID,Active,Age,D,P,Project,Tags,R,S,Due,Until,Description,Urg
	report.ready.columns=id,start.age,entry.age,depends.indicator,priority,project,tags,recur.indicator,scheduled.countdown,due.countdown,until.remaining,description,urgency
	report.ready.filter=+READY
	report.ready.sort=start-,urgency-
	report.ready.context=1
	report.blocked.description=Blocked tasks
	report.blocked.columns=id,depends,project,priority,due,start.active,entry.age,description
	report.blocked.labels=ID,Deps,Proj,Pri,Due,Active,Age,Description
	report.blocked.sort=due+,priority-,start-,project+
	report.blocked.filter=+PENDING -WAITING +BLOCKED
	report.blocked.context=1
	report.unblocked.description=Unblocked tasks
	report.unblocked.columns=id,depends,project,priority,due,start.active,entry.age,description
	report.unblocked.labels=ID,Deps,Proj,Pri,Due,Active,Age,Description
	report.unblocked.sort=due+,priority-,start-,project+
	report.unblocked.filter=+PENDING -WAITING -BLOCKED
	report.unblocked.context=1
	report.blocking.description=Blocking tasks
	report.blocking.labels=ID,UUID,A,Deps,Project,Tags,R,W,Sch,Due,Until,Description,Urg
	report.blocking.columns=id,uuid.short,start.active,depends,project,tags,recur,wait,scheduled.remaining,due.relative,until.remaining,description.count,urgency
	report.blocking.sort=urgency-,due+,entry+
	report.blocking.filter=+PENDING -WAITING +BLOCKING
	report.blocking.context=1
	report.timesheet.filter=(+PENDING -WAITING start.after:now-4wks) or (+COMPLETED -WAITING end.after:now-4wks)
	report.timesheet.context=0
	"""#
