# Sourced by `just fixtures`. Each `case_<name>` builds a fresh Replica with `task`, with one Recurrence
# instance generated by a report, then runs the write under test on it with `act`, all within one
# second.

# A weekly Series due in 2030, whose template generates its one instance when a report runs.
series() {
	task add Alpha due:2030-01-01 recur:weekly
	task list
}

instance() {
	task +INSTANCE _uuids
}

case_complete_instance() {
	series
	act "$(instance)" done
}

case_complete_two_instances() {
	# Due two days ago, so the template generates an instance for each day since.
	task add Alpha due:today-2d recur:daily
	task list
	instances=($(instance | head -2))
	act "${instances[@]}" done
}

case_delete_instance() {
	series
	act "$(instance)" delete
}

case_mark_completed_instance_pending() {
	series
	task "$(instance)" done
	act "$(instance)" modify status:pending
}

case_remove_wait_from_instance() {
	series
	task "$(instance)" modify wait:2029-12-01
	act "$(instance)" modify wait:
}

case_set_description_of_instance() {
	series
	act "$(instance)" modify description:Beta
}

case_set_wait_on_instance() {
	series
	act "$(instance)" modify wait:2029-12-01
}

case_start_instance() {
	series
	act "$(instance)" start
}
