// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(EngineFFI)
import EngineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_engine_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_engine_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureEngineInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * One open Replica. Every call is a short, synchronous transaction: the CLI waits at most 5 s on a
 * held lock, so nothing here holds one open between calls.
 */
public protocol EngineHandleProtocol: AnyObject, Sendable {
    
    /**
     * Commits `operations` as one Undo point, but only if every expectation still holds just
     * before the commit. TaskChampion's commit never checks an update's old value, so without this
     * a plan made from a stale snapshot would overwrite whatever changed since. A write landing
     * between the check and the commit still gets through, as it does for the CLI.
     */
    func apply(operations: [PlannedOperation], expectations: [Expectation]) throws  -> ApplyOutcome
    
    /**
     * Reverts `operations` if they are still TaskChampion's newest undo operations.
     */
    func commitReversedOperations(operations: [UndoOperation]) throws  -> UndoOutcome
    
    /**
     * Changes whenever any connection, the app's own included, commits to the Replica.
     */
    func dataVersion() throws  -> Int64
    
    /**
     * The operations since the newest undo point, which starts them.
     */
    func getUndoOperations() throws  -> [UndoOperation]
    
    /**
     * Reads every task and the working set. They come from separate transactions, so the read is
     * retried until `data_version` holds across it.
     */
    func snapshot() throws  -> Snapshot
    
}
/**
 * One open Replica. Every call is a short, synchronous transaction: the CLI waits at most 5 s on a
 * held lock, so nothing here holds one open between calls.
 */
open class EngineHandle: EngineHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_engine_fn_clone_enginehandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_engine_fn_free_enginehandle(handle, $0) }
    }

    
    /**
     * Opens the Replica in `directory`, refusing a folder without one rather than creating it, and
     * a schema major version newer than this engine reads.
     */
public static func `open`(directory: String)throws  -> EngineHandle  {
    return try  FfiConverterTypeEngineHandle_lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_constructor_enginehandle_open(
        FfiConverterString.lower(directory),uniffiCallStatus
    )
})
}
    

    
    /**
     * Commits `operations` as one Undo point, but only if every expectation still holds just
     * before the commit. TaskChampion's commit never checks an update's old value, so without this
     * a plan made from a stale snapshot would overwrite whatever changed since. A write landing
     * between the check and the commit still gets through, as it does for the CLI.
     */
open func apply(operations: [PlannedOperation], expectations: [Expectation])throws  -> ApplyOutcome  {
    return try  FfiConverterTypeApplyOutcome_lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_method_enginehandle_apply(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypePlannedOperation.lower(operations),
        FfiConverterSequenceTypeExpectation.lower(expectations),uniffiCallStatus
    )
})
}
    
    /**
     * Reverts `operations` if they are still TaskChampion's newest undo operations.
     */
open func commitReversedOperations(operations: [UndoOperation])throws  -> UndoOutcome  {
    return try  FfiConverterTypeUndoOutcome_lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_method_enginehandle_commit_reversed_operations(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeUndoOperation.lower(operations),uniffiCallStatus
    )
})
}
    
    /**
     * Changes whenever any connection, the app's own included, commits to the Replica.
     */
open func dataVersion()throws  -> Int64  {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_method_enginehandle_data_version(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * The operations since the newest undo point, which starts them.
     */
open func getUndoOperations()throws  -> [UndoOperation]  {
    return try  FfiConverterSequenceTypeUndoOperation.lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_method_enginehandle_get_undo_operations(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Reads every task and the working set. They come from separate transactions, so the read is
     * retried until `data_version` holds across it.
     */
open func snapshot()throws  -> Snapshot  {
    return try  FfiConverterTypeSnapshot_lift(try rustCallWithError(FfiConverterTypeEngineError_lift) {
        uniffiCallStatus in
    uniffi_engine_fn_method_enginehandle_snapshot(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = EngineHandle

    public static func lift(_ handle: UInt64) throws -> EngineHandle {
        return EngineHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: EngineHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: EngineHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineHandle_lift(_ handle: UInt64) throws -> EngineHandle {
    return try FfiConverterTypeEngineHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineHandle_lower(_ value: EngineHandle) -> UInt64 {
    return FfiConverterTypeEngineHandle.lower(value)
}




/**
 * A value the planner read, which must still hold for its plan to commit. A missing task reads
 * every property as `None`.
 */
public struct Expectation: Equatable, Hashable {
    public var uuid: String
    public var property: String
    public var value: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, property: String, value: String?) {
        self.uuid = uuid
        self.property = property
        self.value = value
    }

    

    
}

#if compiler(>=6)
extension Expectation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExpectation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Expectation {
        return
            try Expectation(
                uuid: FfiConverterString.read(from: &buf), 
                property: FfiConverterString.read(from: &buf), 
                value: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Expectation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterString.write(value.property, into: &buf)
        FfiConverterOptionString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExpectation_lift(_ buf: RustBuffer) throws -> Expectation {
    return try FfiConverterTypeExpectation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExpectation_lower(_ value: Expectation) -> RustBuffer {
    return FfiConverterTypeExpectation.lower(value)
}


/**
 * A coherent read of a Replica: every task and the working set, as of `data_version`.
 */
public struct Snapshot: Equatable, Hashable {
    public var dataVersion: Int64
    public var tasks: [TaskProperties]
    public var workingSet: [WorkingSetEntry]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(dataVersion: Int64, tasks: [TaskProperties], workingSet: [WorkingSetEntry]) {
        self.dataVersion = dataVersion
        self.tasks = tasks
        self.workingSet = workingSet
    }

    

    
}

#if compiler(>=6)
extension Snapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Snapshot {
        return
            try Snapshot(
                dataVersion: FfiConverterInt64.read(from: &buf), 
                tasks: FfiConverterSequenceTypeTaskProperties.read(from: &buf), 
                workingSet: FfiConverterSequenceTypeWorkingSetEntry.read(from: &buf)
        )
    }

    public static func write(_ value: Snapshot, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.dataVersion, into: &buf)
        FfiConverterSequenceTypeTaskProperties.write(value.tasks, into: &buf)
        FfiConverterSequenceTypeWorkingSetEntry.write(value.workingSet, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnapshot_lift(_ buf: RustBuffer) throws -> Snapshot {
    return try FfiConverterTypeSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSnapshot_lower(_ value: Snapshot) -> RustBuffer {
    return FfiConverterTypeSnapshot.lower(value)
}


/**
 * Named so the generated Swift type doesn't shadow Swift's `Task`.
 */
public struct TaskProperties: Equatable, Hashable {
    public var uuid: String
    public var properties: [String: String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, properties: [String: String]) {
        self.uuid = uuid
        self.properties = properties
    }

    

    
}

#if compiler(>=6)
extension TaskProperties: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskProperties: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskProperties {
        return
            try TaskProperties(
                uuid: FfiConverterString.read(from: &buf), 
                properties: FfiConverterDictionaryStringString.read(from: &buf)
        )
    }

    public static func write(_ value: TaskProperties, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterDictionaryStringString.write(value.properties, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskProperties_lift(_ buf: RustBuffer) throws -> TaskProperties {
    return try FfiConverterTypeTaskProperties.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskProperties_lower(_ value: TaskProperties) -> RustBuffer {
    return FfiConverterTypeTaskProperties.lower(value)
}


public struct WorkingSetEntry: Equatable, Hashable {
    public var id: UInt64
    public var uuid: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt64, uuid: String) {
        self.id = id
        self.uuid = uuid
    }

    

    
}

#if compiler(>=6)
extension WorkingSetEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkingSetEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkingSetEntry {
        return
            try WorkingSetEntry(
                id: FfiConverterUInt64.read(from: &buf), 
                uuid: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WorkingSetEntry, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.uuid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkingSetEntry_lift(_ buf: RustBuffer) throws -> WorkingSetEntry {
    return try FfiConverterTypeWorkingSetEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkingSetEntry_lower(_ value: WorkingSetEntry) -> RustBuffer {
    return FfiConverterTypeWorkingSetEntry.lower(value)
}



public enum ApplyOutcome: Equatable, Hashable {
    
    case committed
    /**
     * Nothing was committed, because these tasks no longer match the expectations.
     */
    case conflict(uuids: [String]
    )





}

#if compiler(>=6)
extension ApplyOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApplyOutcome: FfiConverterRustBuffer {
    typealias SwiftType = ApplyOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApplyOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .committed
        
        case 2: return .conflict(uuids: try FfiConverterSequenceString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ApplyOutcome, into buf: inout [UInt8]) {
        switch value {
        
        
        case .committed:
            writeInt(&buf, Int32(1))
        
        
        case let .conflict(uuids):
            writeInt(&buf, Int32(2))
            FfiConverterSequenceString.write(uuids, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApplyOutcome_lift(_ buf: RustBuffer) throws -> ApplyOutcome {
    return try FfiConverterTypeApplyOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApplyOutcome_lower(_ value: ApplyOutcome) -> RustBuffer {
    return FfiConverterTypeApplyOutcome.lower(value)
}



public 
enum EngineError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Failed(message: String
    )
    /**
     * The folder has no TaskChampion database.
     */
    case NotAReplica
    /**
     * The database's schema major version is newer than this engine reads.
     */
    case UnsupportedSchema(major: UInt32, minor: UInt32
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension EngineError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotAReplica
        case 3: return .UnsupportedSchema(
            major: try FfiConverterUInt32.read(from: &buf), 
            minor: try FfiConverterUInt32.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .NotAReplica:
            writeInt(&buf, Int32(2))
        
        
        case let .UnsupportedSchema(major,minor):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(major, into: &buf)
            FfiConverterUInt32.write(minor, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineError_lift(_ buf: RustBuffer) throws -> EngineError {
    return try FfiConverterTypeEngineError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineError_lower(_ value: EngineError) -> RustBuffer {
    return FfiConverterTypeEngineError.lower(value)
}


/**
 * One change in a batch passed to `apply`. Each writes exactly what it names.
 */

public enum PlannedOperation: Equatable, Hashable {
    
    case create(uuid: String
    )
    /**
     * Writes `status` alone. TaskChampion adds a task to the working set when it becomes pending
     * or recurring; stamping `end` is the planner's job.
     */
    case setStatus(uuid: String, status: Status
    )
    /**
     * Removes the property when `value` is `None`.
     */
    case setValue(uuid: String, property: String, value: String?
    )





}

#if compiler(>=6)
extension PlannedOperation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlannedOperation: FfiConverterRustBuffer {
    typealias SwiftType = PlannedOperation

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlannedOperation {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .create(uuid: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .setStatus(uuid: try FfiConverterString.read(from: &buf), status: try FfiConverterTypeStatus.read(from: &buf)
        )
        
        case 3: return .setValue(uuid: try FfiConverterString.read(from: &buf), property: try FfiConverterString.read(from: &buf), value: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PlannedOperation, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .create(uuid):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .setStatus(uuid,status):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(uuid, into: &buf)
            FfiConverterTypeStatus.write(status, into: &buf)
            
        
        case let .setValue(uuid,property,value):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(uuid, into: &buf)
            FfiConverterString.write(property, into: &buf)
            FfiConverterOptionString.write(value, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlannedOperation_lift(_ buf: RustBuffer) throws -> PlannedOperation {
    return try FfiConverterTypePlannedOperation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlannedOperation_lower(_ value: PlannedOperation) -> RustBuffer {
    return FfiConverterTypePlannedOperation.lower(value)
}




public enum Status: Equatable, Hashable {
    
    case completed
    case deleted
    case pending
    case recurring





}

#if compiler(>=6)
extension Status: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStatus: FfiConverterRustBuffer {
    typealias SwiftType = Status

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Status {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .completed
        
        case 2: return .deleted
        
        case 3: return .pending
        
        case 4: return .recurring
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Status, into buf: inout [UInt8]) {
        switch value {
        
        
        case .completed:
            writeInt(&buf, Int32(1))
        
        
        case .deleted:
            writeInt(&buf, Int32(2))
        
        
        case .pending:
            writeInt(&buf, Int32(3))
        
        
        case .recurring:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatus_lift(_ buf: RustBuffer) throws -> Status {
    return try FfiConverterTypeStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatus_lower(_ value: Status) -> RustBuffer {
    return FfiConverterTypeStatus.lower(value)
}



/**
 * TaskChampion's `Operation`, renamed so the generated Swift type doesn't shadow Foundation's.
 * Pass these back to `commit_reversed_operations` unchanged: TaskChampion reverses them only when
 * they equal its newest undo operations exactly, timestamps included, which is why the timestamp
 * crosses as integer nanoseconds rather than a lossy `Date`.
 */

public enum UndoOperation: Equatable, Hashable {
    
    case create(uuid: String
    )
    case delete(uuid: String, oldTask: [String: String]
    )
    case update(uuid: String, property: String, oldValue: String?, value: String?, timestampNanoseconds: Int64
    )
    case undoPoint





}

#if compiler(>=6)
extension UndoOperation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUndoOperation: FfiConverterRustBuffer {
    typealias SwiftType = UndoOperation

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UndoOperation {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .create(uuid: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .delete(uuid: try FfiConverterString.read(from: &buf), oldTask: try FfiConverterDictionaryStringString.read(from: &buf)
        )
        
        case 3: return .update(uuid: try FfiConverterString.read(from: &buf), property: try FfiConverterString.read(from: &buf), oldValue: try FfiConverterOptionString.read(from: &buf), value: try FfiConverterOptionString.read(from: &buf), timestampNanoseconds: try FfiConverterInt64.read(from: &buf)
        )
        
        case 4: return .undoPoint
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UndoOperation, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .create(uuid):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .delete(uuid,oldTask):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(uuid, into: &buf)
            FfiConverterDictionaryStringString.write(oldTask, into: &buf)
            
        
        case let .update(uuid,property,oldValue,value,timestampNanoseconds):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(uuid, into: &buf)
            FfiConverterString.write(property, into: &buf)
            FfiConverterOptionString.write(oldValue, into: &buf)
            FfiConverterOptionString.write(value, into: &buf)
            FfiConverterInt64.write(timestampNanoseconds, into: &buf)
            
        
        case .undoPoint:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoOperation_lift(_ buf: RustBuffer) throws -> UndoOperation {
    return try FfiConverterTypeUndoOperation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoOperation_lower(_ value: UndoOperation) -> RustBuffer {
    return FfiConverterTypeUndoOperation.lower(value)
}




public enum UndoOutcome: Equatable, Hashable {
    
    /**
     * The operations were no longer TaskChampion's newest undo point, so nothing changed.
     */
    case notApplied
    /**
     * The reversal committed, so the snapshot needs refreshing. `error` is a failure that followed
     * it, while TaskChampion rebuilt the working set.
     */
    case applied(error: String?
    )





}

#if compiler(>=6)
extension UndoOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUndoOutcome: FfiConverterRustBuffer {
    typealias SwiftType = UndoOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UndoOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notApplied
        
        case 2: return .applied(error: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UndoOutcome, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notApplied:
            writeInt(&buf, Int32(1))
        
        
        case let .applied(error):
            writeInt(&buf, Int32(2))
            FfiConverterOptionString.write(error, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoOutcome_lift(_ buf: RustBuffer) throws -> UndoOutcome {
    return try FfiConverterTypeUndoOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoOutcome_lower(_ value: UndoOutcome) -> RustBuffer {
    return FfiConverterTypeUndoOutcome.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeExpectation: FfiConverterRustBuffer {
    typealias SwiftType = [Expectation]

    public static func write(_ value: [Expectation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeExpectation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Expectation] {
        let len: Int32 = try readInt(&buf)
        var seq = [Expectation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeExpectation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTaskProperties: FfiConverterRustBuffer {
    typealias SwiftType = [TaskProperties]

    public static func write(_ value: [TaskProperties], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTaskProperties.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TaskProperties] {
        let len: Int32 = try readInt(&buf)
        var seq = [TaskProperties]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTaskProperties.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkingSetEntry: FfiConverterRustBuffer {
    typealias SwiftType = [WorkingSetEntry]

    public static func write(_ value: [WorkingSetEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkingSetEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkingSetEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkingSetEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkingSetEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePlannedOperation: FfiConverterRustBuffer {
    typealias SwiftType = [PlannedOperation]

    public static func write(_ value: [PlannedOperation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePlannedOperation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PlannedOperation] {
        let len: Int32 = try readInt(&buf)
        var seq = [PlannedOperation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePlannedOperation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUndoOperation: FfiConverterRustBuffer {
    typealias SwiftType = [UndoOperation]

    public static func write(_ value: [UndoOperation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUndoOperation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UndoOperation] {
        let len: Int32 = try readInt(&buf)
        var seq = [UndoOperation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUndoOperation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_engine_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_engine_checksum_method_enginehandle_apply() != 53698) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_method_enginehandle_commit_reversed_operations() != 43696) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_method_enginehandle_data_version() != 28298) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_method_enginehandle_get_undo_operations() != 41200) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_method_enginehandle_snapshot() != 63241) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_constructor_enginehandle_open() != 52432) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureEngineInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all